/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.medicalCentre.view;

import com.sun.glass.ui.Cursor;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;

/**
 *
 * @author pasindu
 */
public class Demo extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
        setLocationRelativeTo(null);
        setDate();
        setTitle("Greenway Health Home");
        pnlMain.setBackground(new Color(0,0,0,0f));
        lblUser.setText(new LoginPage().sendUserName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogOut = new org.jdesktop.swingx.JXButton();
        btnAppointement = new org.jdesktop.swingx.JXButton();
        btnPayment = new org.jdesktop.swingx.JXButton();
        btnDocSession = new org.jdesktop.swingx.JXButton();
        btnDocDetail = new org.jdesktop.swingx.JXButton();
        btnSettings = new org.jdesktop.swingx.JXButton();
        lblTime = new org.jdesktop.swingx.JXLabel();
        lblDate = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        lblUser = new org.jdesktop.swingx.JXLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        btnSearchDoctor = new org.jdesktop.swingx.JXButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jXButton1 = new org.jdesktop.swingx.JXButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 860, 610));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 860, 610));
        setMinimumSize(new java.awt.Dimension(1283, 730));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlMain.setPreferredSize(new java.awt.Dimension(790, 560));
        pnlMain.setLayout(null);
        getContentPane().add(pnlMain);
        pnlMain.setBounds(440, 140, 830, 560);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/medicalCentre/image/greenway_splash-screen6.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 0, 320, 120);

        btnLogOut.setText("Log Out");
        btnLogOut.setToolTipText("Close the programme");
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
        });
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut);
        btnLogOut.setBounds(10, 630, 200, 68);

        btnAppointement.setText("Make an Appointement");
        btnAppointement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppointementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppointementMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAppointementMouseClicked(evt);
            }
        });
        btnAppointement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointementActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppointement);
        btnAppointement.setBounds(10, 150, 200, 70);

        btnPayment.setText("Payments");
        btnPayment.setToolTipText("Set appointement payments");
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaymentMouseExited(evt);
            }
        });
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btnPayment);
        btnPayment.setBounds(10, 310, 200, 71);

        btnDocSession.setText("Doctor Sessions");
        btnDocSession.setToolTipText("Create new doctor sessions");
        btnDocSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDocSessionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDocSessionMouseExited(evt);
            }
        });
        btnDocSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocSessionActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocSession);
        btnDocSession.setBounds(10, 390, 200, 69);

        btnDocDetail.setText("Doctor Details");
        btnDocDetail.setToolTipText("Insert new doctors and details");
        btnDocDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDocDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDocDetailMouseExited(evt);
            }
        });
        btnDocDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocDetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocDetail);
        btnDocDetail.setBounds(10, 470, 200, 69);

        btnSettings.setText("Settings");
        btnSettings.setToolTipText("Handle passwods");
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingsMouseExited(evt);
            }
        });
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSettings);
        btnSettings.setBounds(10, 550, 200, 68);

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(lblTime);
        lblTime.setBounds(1130, 40, 150, 40);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(lblDate);
        lblDate.setBounds(1130, 0, 150, 40);

        jXLabel2.setText("Time");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jXLabel2);
        jXLabel2.setBounds(1000, 40, 110, 40);
        getContentPane().add(lblUser);
        lblUser.setBounds(100, 0, 110, 30);

        jXLabel1.setText("Date ");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(jXLabel1);
        jXLabel1.setBounds(1000, 0, 110, 40);

        btnSearchDoctor.setText("Search Doctors");
        btnSearchDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchDoctorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchDoctorMouseExited(evt);
            }
        });
        btnSearchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchDoctor);
        btnSearchDoctor.setBounds(10, 230, 200, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("User :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/medicalCentre/image/medical-wallpapers.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1290, 730);

        jXButton1.setText("jXButton1");
        getContentPane().add(jXButton1);
        jXButton1.setBounds(240, 270, 140, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
      
        int result=JOptionPane.showConfirmDialog(null, "Do you want to Log Out ?", "Log Out", JOptionPane.YES_NO_OPTION);
        if(result==0){
            Demo.this.dispose();
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed

        PaymentPanel payment =new PaymentPanel();
        pnlMain.removeAll();
        payment.setSize(pnlMain.getSize());
        pnlMain.add(payment);
        pnlMain.repaint();
        pnlMain.revalidate();
        payment.setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnDocSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocSessionActionPerformed

        DoctorSessionPanel docSession=new DoctorSessionPanel();
        pnlMain.removeAll();
        docSession.setSize(pnlMain.getSize());
        pnlMain.add(docSession);
        pnlMain.repaint();
        pnlMain.revalidate();
        docSession.setVisible(true);
    }//GEN-LAST:event_btnDocSessionActionPerformed

    private void btnDocDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocDetailActionPerformed

        DoctorDetailPanel docDetail=new DoctorDetailPanel();
        pnlMain.removeAll();
        docDetail.setSize(pnlMain.getSize());
        pnlMain.add(docDetail);
        pnlMain.repaint();
        pnlMain.revalidate();
        docDetail.setVisible(true);
    }//GEN-LAST:event_btnDocDetailActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed

        SettingsPanel settings=new SettingsPanel();
        pnlMain.removeAll();
        settings.setSize(pnlMain.getSize());
        pnlMain.add(settings);
        pnlMain.repaint();
        pnlMain.revalidate();
        settings.setVisible(true);
    }//GEN-LAST:event_btnSettingsActionPerformed
    
    private void btnPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseEntered
        btnPayment.setFont(new Font("Tahoma",Font.BOLD,14));
    }//GEN-LAST:event_btnPaymentMouseEntered

    private void btnPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseExited
        btnPayment.setFont(new Font("Tahoma",0,11));
    }//GEN-LAST:event_btnPaymentMouseExited

    private void btnDocSessionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocSessionMouseEntered
        btnDocSession.setFont(new Font("Tahoma",Font.BOLD,14));
    }//GEN-LAST:event_btnDocSessionMouseEntered

    private void btnDocSessionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocSessionMouseExited
        btnDocSession.setFont(new Font("Tahoma",0,11));
    }//GEN-LAST:event_btnDocSessionMouseExited

    private void btnDocDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocDetailMouseEntered
        btnDocDetail.setFont(new Font("Tahoma",Font.BOLD,14));
    }//GEN-LAST:event_btnDocDetailMouseEntered

    private void btnDocDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocDetailMouseExited
       btnDocDetail.setFont(new Font("Tahoma",0,11));
    }//GEN-LAST:event_btnDocDetailMouseExited

    private void btnSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseEntered
        btnSettings.setFont(new Font("Tahoma",Font.BOLD,14));
    }//GEN-LAST:event_btnSettingsMouseEntered

    private void btnSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMouseExited
        btnSettings.setFont(new Font("Tahoma",0,11));
    }//GEN-LAST:event_btnSettingsMouseExited

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        btnLogOut.setFont(new Font("Tahoma",Font.BOLD,14));
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        btnLogOut.setFont(new Font("Tahoma",0,11));
    }//GEN-LAST:event_btnLogOutMouseExited

    private void btnAppointementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointementActionPerformed
        NewAppointementPanel appointement=new NewAppointementPanel();
        pnlMain.removeAll();
        appointement.setSize(pnlMain.getSize());
        pnlMain.add(appointement);
        pnlMain.repaint();
        pnlMain.revalidate();
        appointement.setVisible(true);
    }//GEN-LAST:event_btnAppointementActionPerformed

    private void btnAppointementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointementMouseEntered
        btnAppointement.setFont(new Font("Tahoma",Font.BOLD,14));
    }//GEN-LAST:event_btnAppointementMouseEntered

    private void btnAppointementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointementMouseExited
        btnAppointement.setFont(new Font("Tahoma",0,11));
    }//GEN-LAST:event_btnAppointementMouseExited

    private void btnAppointementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointementMouseClicked
        NewAppointementPanel appointement=new NewAppointementPanel();
        pnlMain.removeAll();
        appointement.setSize(pnlMain.getSize());
        pnlMain.add(appointement);
        pnlMain.repaint();
        pnlMain.revalidate();
        appointement.setVisible(true);
    }//GEN-LAST:event_btnAppointementMouseClicked

    private void btnSearchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDoctorActionPerformed
        DoctorSearch docSearch=new DoctorSearch();
        pnlMain.removeAll();
        docSearch.setSize(pnlMain.getSize());
        pnlMain.add(docSearch);
        pnlMain.repaint();
        pnlMain.revalidate();
        docSearch.setVisible(true);
    }//GEN-LAST:event_btnSearchDoctorActionPerformed

    private void btnSearchDoctorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchDoctorMouseEntered
        btnSearchDoctor.setFont(new Font("Tahoma",Font.BOLD,14));
    }//GEN-LAST:event_btnSearchDoctorMouseEntered

    private void btnSearchDoctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchDoctorMouseExited
        btnSearchDoctor.setFont(new Font("Tahoma",0,11));
    }//GEN-LAST:event_btnSearchDoctorMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //----Check these steps
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnAppointement;
    private org.jdesktop.swingx.JXButton btnDocDetail;
    private org.jdesktop.swingx.JXButton btnDocSession;
    private org.jdesktop.swingx.JXButton btnLogOut;
    private org.jdesktop.swingx.JXButton btnPayment;
    private org.jdesktop.swingx.JXButton btnSearchDoctor;
    private org.jdesktop.swingx.JXButton btnSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel lblDate;
    private org.jdesktop.swingx.JXLabel lblTime;
    private org.jdesktop.swingx.JXLabel lblUser;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Calendar currentCalendar = Calendar.getInstance();
        Date currentTime = currentCalendar.getTime();
        SimpleDateFormat timeFormat = new SimpleDateFormat("dd-MM-yyyy ");
        lblDate.setText(timeFormat.format(currentTime));
    
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    Date date = new Date();
                    String time = new SimpleDateFormat("hh:mm:ss aa").format(date);
                    lblTime.setText(time);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {

                    }
                }
            }
        }).start();
    }
}
