/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ac.uok.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ac.uok.dao.db.DBConnection;
import lk.ac.uok.validation.Validation;

/**
 *
 * @author pasindu
 */
public class SettingsPanel extends javax.swing.JPanel {
    String currentUser;
    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
        txtNewUser.requestFocus();
    }
    public SettingsPanel(String user) {
        initComponents();
        txtNewUser.requestFocus();
        this.currentUser=user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        btnClearPW = new org.jdesktop.swingx.JXButton();
        btnUpdatePW = new org.jdesktop.swingx.JXButton();
        txtConfirmPW = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtNewPW = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtCurrentPW = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        btnClearUN = new javax.swing.JButton();
        btnUpdateUN = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtNewUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jLabel1 = new javax.swing.JLabel();

        btnClearPW.setText("Clear");
        btnClearPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPWActionPerformed(evt);
            }
        });

        btnUpdatePW.setText("Update");
        btnUpdatePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePWActionPerformed(evt);
            }
        });

        txtConfirmPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPWActionPerformed(evt);
            }
        });

        jLabel7.setText("Confirm Password");

        txtNewPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPWActionPerformed(evt);
            }
        });

        jLabel6.setText("New PassWord");

        txtCurrentPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentPWActionPerformed(evt);
            }
        });

        jLabel5.setText("Current  PassWord");

        jXLabel1.setText("Change Current Password");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnClearUN.setText("Clear");
        btnClearUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearUNActionPerformed(evt);
            }
        });

        btnUpdateUN.setText("Update");
        btnUpdateUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUNActionPerformed(evt);
            }
        });

        jLabel4.setText("Current  PassWord");

        txtNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewUserActionPerformed(evt);
            }
        });

        jLabel2.setText("New  UserName");

        jXLabel2.setText("Add new User");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Settings");

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(txtNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(txtCurrentPW, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(txtNewPW, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateUN, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClearUN, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdatePW, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClearPW, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmPW, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateUN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearUN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentPW, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPW, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmPW, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdatePW, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearPW, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPWActionPerformed
        clearAll();
    }//GEN-LAST:event_btnClearPWActionPerformed

    private void btnClearUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearUNActionPerformed
        txtNewUser.setText("");
        txtNewUser.requestFocus();
        txtPassword.setText("");
    }//GEN-LAST:event_btnClearUNActionPerformed

    private void btnUpdateUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUNActionPerformed
        if(Validation.validateText(txtNewUser.getText())){
            JOptionPane.showMessageDialog(null, "Please Enter the user name");
            txtNewUser.requestFocus();
            return;
        }
        if(Validation.validateText(txtPassword.getText())){
           JOptionPane.showMessageDialog(null, "Please Enter the password");
            txtNewUser.requestFocus();
            return; 
        }
        Connection conn=DBConnection.getInstance().getConnection();
        String sql="insert into login values(?,?,?);";
        try {
            PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.setObject(1,null);
            pstm.setObject(2, txtNewUser.getText());
            pstm.setObject(3, txtPassword.getText());
            int affectedRows=pstm.executeUpdate();
            if(affectedRows>0)
                JOptionPane.showMessageDialog(this,"User added");
            else
                JOptionPane.showMessageDialog(this, "Error occured");
        } catch (SQLException ex) {
            Logger.getLogger(SettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNewUser.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnUpdateUNActionPerformed

    private void txtNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewUserActionPerformed

    private void btnUpdatePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePWActionPerformed
        if(Validation.validateText(txtCurrentPW.getText())){
            JOptionPane.showMessageDialog(null, "Please Enter the current password");
            txtCurrentPW.requestFocus();
            return;
        }
        if(Validation.validateText(txtNewPW.getText())){
            JOptionPane.showMessageDialog(null, "Please Enter the new password");
            txtNewPW.requestFocus();
            return;
        }
        if(Validation.validateText(txtConfirmPW.getText())){
            JOptionPane.showMessageDialog(null, "Please Enter the new password again");
            txtConfirmPW.requestFocus();
            return;
        }
        Connection connection=DBConnection.getInstance().getConnection();
        String sql="select * from login where username=? and password=?;";
        sql = "SELECT * FROM login WHERE username='"+currentUser+"' and password='"+txtCurrentPW.getText()+"' ";
        try {
            //PreparedStatement pstm=connection.prepareStatement(sql);
            Statement stm=connection.createStatement();
            //pstm.setObject(1, currentUser);
           //pstm.setObject(2, txtCurrentPW);
            ResultSet rst=stm.executeQuery(sql);
            
            //ResultSet rst=stm.executeQuery();
            //System.out.println(rst.getObject(2));
            if(rst.next()){
                sql="update login set password=? where username=? and password=?;";
                PreparedStatement pstm=connection.prepareStatement(sql);
                pstm=connection.prepareStatement(sql); 
                pstm.setObject(1,txtNewPW.getText());
                pstm.setObject(2,currentUser);
                pstm.setObject(3,txtCurrentPW.getText());
                int affectedRows=pstm.executeUpdate();
                if(affectedRows>0)
                    JOptionPane.showMessageDialog(this, "Password Changed");
                
            }else{
                    JOptionPane.showMessageDialog(this, "Incorrect current password");
                    clearAll();
                    txtCurrentPW.requestFocus();
            }
                
        } catch (SQLException ex) {
            Logger.getLogger(SettingsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnUpdatePWActionPerformed

    private void txtCurrentPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentPWActionPerformed
        txtNewPW.requestFocus();;
    }//GEN-LAST:event_txtCurrentPWActionPerformed

    private void txtNewPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPWActionPerformed
        txtConfirmPW.requestFocus();
    }//GEN-LAST:event_txtNewPWActionPerformed

    private void txtConfirmPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPWActionPerformed
        btnUpdatePW.requestFocus();;
    }//GEN-LAST:event_txtConfirmPWActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnClearPW;
    private javax.swing.JButton btnClearUN;
    private org.jdesktop.swingx.JXButton btnUpdatePW;
    private javax.swing.JButton btnUpdateUN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private javax.swing.JPasswordField txtConfirmPW;
    private javax.swing.JPasswordField txtCurrentPW;
    private javax.swing.JPasswordField txtNewPW;
    private javax.swing.JTextField txtNewUser;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        txtCurrentPW.setText("");
        txtCurrentPW.requestFocus();
        txtNewPW.setText("");
        txtConfirmPW.setText("");
    }
}
